# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gillis/holoduke.nl/footballmanager/server/simulatornative

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gillis/holoduke.nl/footballmanager/server/simulatornative

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gillis/holoduke.nl/footballmanager/server/simulatornative/CMakeFiles /home/gillis/holoduke.nl/footballmanager/server/simulatornative/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gillis/holoduke.nl/footballmanager/server/simulatornative/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named footballsimulator2

# Build rule for target.
footballsimulator2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 footballsimulator2
.PHONY : footballsimulator2

# fast build rule for target.
footballsimulator2/fast:
	$(MAKE) -f CMakeFiles/footballsimulator2.dir/build.make CMakeFiles/footballsimulator2.dir/build
.PHONY : footballsimulator2/fast

Communication.o: Communication.cpp.o

.PHONY : Communication.o

# target to build an object file
Communication.cpp.o:
	$(MAKE) -f CMakeFiles/footballsimulator2.dir/build.make CMakeFiles/footballsimulator2.dir/Communication.cpp.o
.PHONY : Communication.cpp.o

Communication.i: Communication.cpp.i

.PHONY : Communication.i

# target to preprocess a source file
Communication.cpp.i:
	$(MAKE) -f CMakeFiles/footballsimulator2.dir/build.make CMakeFiles/footballsimulator2.dir/Communication.cpp.i
.PHONY : Communication.cpp.i

Communication.s: Communication.cpp.s

.PHONY : Communication.s

# target to generate assembly for a file
Communication.cpp.s:
	$(MAKE) -f CMakeFiles/footballsimulator2.dir/build.make CMakeFiles/footballsimulator2.dir/Communication.cpp.s
.PHONY : Communication.cpp.s

Lineup.o: Lineup.cpp.o

.PHONY : Lineup.o

# target to build an object file
Lineup.cpp.o:
	$(MAKE) -f CMakeFiles/footballsimulator2.dir/build.make CMakeFiles/footballsimulator2.dir/Lineup.cpp.o
.PHONY : Lineup.cpp.o

Lineup.i: Lineup.cpp.i

.PHONY : Lineup.i

# target to preprocess a source file
Lineup.cpp.i:
	$(MAKE) -f CMakeFiles/footballsimulator2.dir/build.make CMakeFiles/footballsimulator2.dir/Lineup.cpp.i
.PHONY : Lineup.cpp.i

Lineup.s: Lineup.cpp.s

.PHONY : Lineup.s

# target to generate assembly for a file
Lineup.cpp.s:
	$(MAKE) -f CMakeFiles/footballsimulator2.dir/build.make CMakeFiles/footballsimulator2.dir/Lineup.cpp.s
.PHONY : Lineup.cpp.s

MatchReport.o: MatchReport.cpp.o

.PHONY : MatchReport.o

# target to build an object file
MatchReport.cpp.o:
	$(MAKE) -f CMakeFiles/footballsimulator2.dir/build.make CMakeFiles/footballsimulator2.dir/MatchReport.cpp.o
.PHONY : MatchReport.cpp.o

MatchReport.i: MatchReport.cpp.i

.PHONY : MatchReport.i

# target to preprocess a source file
MatchReport.cpp.i:
	$(MAKE) -f CMakeFiles/footballsimulator2.dir/build.make CMakeFiles/footballsimulator2.dir/MatchReport.cpp.i
.PHONY : MatchReport.cpp.i

MatchReport.s: MatchReport.cpp.s

.PHONY : MatchReport.s

# target to generate assembly for a file
MatchReport.cpp.s:
	$(MAKE) -f CMakeFiles/footballsimulator2.dir/build.make CMakeFiles/footballsimulator2.dir/MatchReport.cpp.s
.PHONY : MatchReport.cpp.s

MoveOption.o: MoveOption.cpp.o

.PHONY : MoveOption.o

# target to build an object file
MoveOption.cpp.o:
	$(MAKE) -f CMakeFiles/footballsimulator2.dir/build.make CMakeFiles/footballsimulator2.dir/MoveOption.cpp.o
.PHONY : MoveOption.cpp.o

MoveOption.i: MoveOption.cpp.i

.PHONY : MoveOption.i

# target to preprocess a source file
MoveOption.cpp.i:
	$(MAKE) -f CMakeFiles/footballsimulator2.dir/build.make CMakeFiles/footballsimulator2.dir/MoveOption.cpp.i
.PHONY : MoveOption.cpp.i

MoveOption.s: MoveOption.cpp.s

.PHONY : MoveOption.s

# target to generate assembly for a file
MoveOption.cpp.s:
	$(MAKE) -f CMakeFiles/footballsimulator2.dir/build.make CMakeFiles/footballsimulator2.dir/MoveOption.cpp.s
.PHONY : MoveOption.cpp.s

Player.o: Player.cpp.o

.PHONY : Player.o

# target to build an object file
Player.cpp.o:
	$(MAKE) -f CMakeFiles/footballsimulator2.dir/build.make CMakeFiles/footballsimulator2.dir/Player.cpp.o
.PHONY : Player.cpp.o

Player.i: Player.cpp.i

.PHONY : Player.i

# target to preprocess a source file
Player.cpp.i:
	$(MAKE) -f CMakeFiles/footballsimulator2.dir/build.make CMakeFiles/footballsimulator2.dir/Player.cpp.i
.PHONY : Player.cpp.i

Player.s: Player.cpp.s

.PHONY : Player.s

# target to generate assembly for a file
Player.cpp.s:
	$(MAKE) -f CMakeFiles/footballsimulator2.dir/build.make CMakeFiles/footballsimulator2.dir/Player.cpp.s
.PHONY : Player.cpp.s

Position.o: Position.cpp.o

.PHONY : Position.o

# target to build an object file
Position.cpp.o:
	$(MAKE) -f CMakeFiles/footballsimulator2.dir/build.make CMakeFiles/footballsimulator2.dir/Position.cpp.o
.PHONY : Position.cpp.o

Position.i: Position.cpp.i

.PHONY : Position.i

# target to preprocess a source file
Position.cpp.i:
	$(MAKE) -f CMakeFiles/footballsimulator2.dir/build.make CMakeFiles/footballsimulator2.dir/Position.cpp.i
.PHONY : Position.cpp.i

Position.s: Position.cpp.s

.PHONY : Position.s

# target to generate assembly for a file
Position.cpp.s:
	$(MAKE) -f CMakeFiles/footballsimulator2.dir/build.make CMakeFiles/footballsimulator2.dir/Position.cpp.s
.PHONY : Position.cpp.s

Team.o: Team.cpp.o

.PHONY : Team.o

# target to build an object file
Team.cpp.o:
	$(MAKE) -f CMakeFiles/footballsimulator2.dir/build.make CMakeFiles/footballsimulator2.dir/Team.cpp.o
.PHONY : Team.cpp.o

Team.i: Team.cpp.i

.PHONY : Team.i

# target to preprocess a source file
Team.cpp.i:
	$(MAKE) -f CMakeFiles/footballsimulator2.dir/build.make CMakeFiles/footballsimulator2.dir/Team.cpp.i
.PHONY : Team.cpp.i

Team.s: Team.cpp.s

.PHONY : Team.s

# target to generate assembly for a file
Team.cpp.s:
	$(MAKE) -f CMakeFiles/footballsimulator2.dir/build.make CMakeFiles/footballsimulator2.dir/Team.cpp.s
.PHONY : Team.cpp.s

Util.o: Util.cpp.o

.PHONY : Util.o

# target to build an object file
Util.cpp.o:
	$(MAKE) -f CMakeFiles/footballsimulator2.dir/build.make CMakeFiles/footballsimulator2.dir/Util.cpp.o
.PHONY : Util.cpp.o

Util.i: Util.cpp.i

.PHONY : Util.i

# target to preprocess a source file
Util.cpp.i:
	$(MAKE) -f CMakeFiles/footballsimulator2.dir/build.make CMakeFiles/footballsimulator2.dir/Util.cpp.i
.PHONY : Util.cpp.i

Util.s: Util.cpp.s

.PHONY : Util.s

# target to generate assembly for a file
Util.cpp.s:
	$(MAKE) -f CMakeFiles/footballsimulator2.dir/build.make CMakeFiles/footballsimulator2.dir/Util.cpp.s
.PHONY : Util.cpp.s

game.o: game.cpp.o

.PHONY : game.o

# target to build an object file
game.cpp.o:
	$(MAKE) -f CMakeFiles/footballsimulator2.dir/build.make CMakeFiles/footballsimulator2.dir/game.cpp.o
.PHONY : game.cpp.o

game.i: game.cpp.i

.PHONY : game.i

# target to preprocess a source file
game.cpp.i:
	$(MAKE) -f CMakeFiles/footballsimulator2.dir/build.make CMakeFiles/footballsimulator2.dir/game.cpp.i
.PHONY : game.cpp.i

game.s: game.cpp.s

.PHONY : game.s

# target to generate assembly for a file
game.cpp.s:
	$(MAKE) -f CMakeFiles/footballsimulator2.dir/build.make CMakeFiles/footballsimulator2.dir/game.cpp.s
.PHONY : game.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/footballsimulator2.dir/build.make CMakeFiles/footballsimulator2.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/footballsimulator2.dir/build.make CMakeFiles/footballsimulator2.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/footballsimulator2.dir/build.make CMakeFiles/footballsimulator2.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... footballsimulator2"
	@echo "... Communication.o"
	@echo "... Communication.i"
	@echo "... Communication.s"
	@echo "... Lineup.o"
	@echo "... Lineup.i"
	@echo "... Lineup.s"
	@echo "... MatchReport.o"
	@echo "... MatchReport.i"
	@echo "... MatchReport.s"
	@echo "... MoveOption.o"
	@echo "... MoveOption.i"
	@echo "... MoveOption.s"
	@echo "... Player.o"
	@echo "... Player.i"
	@echo "... Player.s"
	@echo "... Position.o"
	@echo "... Position.i"
	@echo "... Position.s"
	@echo "... Team.o"
	@echo "... Team.i"
	@echo "... Team.s"
	@echo "... Util.o"
	@echo "... Util.i"
	@echo "... Util.s"
	@echo "... game.o"
	@echo "... game.i"
	@echo "... game.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

